# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.IntegerField(choices=[(1, 'Part-time'), (2, 'Full-time'), (3, 'Freelance'), (4, 'Contract'), (5, 'Internship')], default=1),
        ),
    ]
