# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 10, 46, 30, 481010, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='job',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 10, 46, 30, 480966, tzinfo=utc)),
        ),
    ]
