# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160820_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 10, 46, 57, 597587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 10, 46, 57, 597544, tzinfo=utc)),
        ),
    ]
