# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20160820_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='update_date',
        ),
        migrations.AddField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 19, 10, 53, 48, 118772, tzinfo=utc)),
        ),
    ]
