# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160820_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 19, 11, 3, 50, 509370, tzinfo=utc)),
        ),
    ]
