# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20160820_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 19, 11, 39, 33, 395105, tzinfo=utc)),
        ),
    ]
