# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20160820_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
