# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import jobsboard.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20160820_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=jobsboard.jobs.models.get_default_expiry),
        ),
    ]
